import { StyleSheet } from 'react-native';
import { STOCKY_COLORS, STOCKY_RADIUS } from '../../theme/tokens';

export const empleadosStyles = StyleSheet.create({
  container: {
    gap: 16,
  },
  listContent: {
    gap: 16,
    paddingBottom: 16,
  },
  heroCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    padding: 16,
    gap: 14,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  heroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  heroTitleWrap: {
    flex: 1,
    gap: 4,
  },
  heroTitle: {
    color: '#111827',
    fontSize: 27 * 1.08,
    fontWeight: '800',
  },
  heroSubtitle: {
    color: '#4B5563',
    fontSize: 17 * 1.08,
    fontWeight: '500',
  },
  heroInviteButtonWrap: {
    borderRadius: 14,
    overflow: 'hidden',
  },
  heroInviteButton: {
    minHeight: 54,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  heroInviteButtonText: {
    color: '#D1D5DB',
    fontSize: 18 * 1.08,
    fontWeight: '600',
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  loadingBlock: {
    minHeight: 100,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadingText: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  emptyText: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  employeeCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#D8E2EC',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  tableHeaderText: {
    color: '#374151',
    fontSize: 12,
    fontWeight: '700',
  },
  cellEmployee: {
    flex: 1.2,
  },
  cellUser: {
    flex: 1.2,
  },
  cellStatus: {
    flex: 1.1,
  },
  cellRole: {
    flex: 1,
  },
  cellAction: {
    flex: 1,
  },
  tableRow: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    minHeight: 62,
    alignItems: 'center',
  },
  tableCell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  initialBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  initialBadgeText: {
    color: '#6B7280',
    fontSize: 14,
    fontWeight: '700',
  },
  employeeName: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '600',
  },
  employeeUsername: {
    color: '#4B5563',
    fontSize: 17,
    fontWeight: '500',
  },
  statusBadge: {
    borderRadius: 999,
    borderWidth: 1,
    minWidth: 104,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    gap: 4,
  },
  statusActive: {
    backgroundColor: '#D1FAE5',
    borderColor: '#BBF7D0',
  },
  statusInactive: {
    backgroundColor: '#E5E7EB',
    borderColor: '#D1D5DB',
  },
  statusBadgeText: {
    fontSize: 15,
    fontWeight: '600',
  },
  statusActiveText: {
    color: '#047857',
  },
  statusInactiveText: {
    color: '#4B5563',
  },
  roleValue: {
    color: '#4B5563',
    fontSize: 16,
    fontWeight: '500',
  },
  deleteActionPill: {
    borderRadius: 12,
    backgroundColor: '#FEE2E2',
    minHeight: 42,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  deleteActionText: {
    color: '#9F1239',
    fontSize: 16,
    fontWeight: '600',
  },
  employeeFormSheet: {
    maxWidth: 560,
    maxHeight: '90%',
    borderRadius: 22,
    borderColor: '#D6DDE7',
    backgroundColor: '#FFFFFF',
  },
  employeeFormHeader: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  employeeFormHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  employeeFormHeaderIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: 'rgba(79,70,229,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  employeeFormHeaderTitleWrap: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  employeeFormHeaderTitle: {
    color: '#111827',
    fontSize: 20,
    fontWeight: '800',
  },
  employeeFormHeaderSubtitle: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '500',
  },
  employeeFormHeaderClose: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(148,163,184,0.12)',
  },
  employeeFormFooter: {
    backgroundColor: '#FFFFFF',
    borderTopColor: '#E5E7EB',
    borderTopWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  employeeFormFooterRow: {
    flexDirection: 'row',
    gap: 10,
  },
  employeeFormCancelButton: {
    minHeight: 45,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D7DEE8',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  employeeFormCancelText: {
    color: '#1F2937',
    fontSize: 14,
    fontWeight: '700',
  },
  employeeFormSaveWrap: {
    flex: 1,
  },
  employeeFormSaveButton: {
    minHeight: 45,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 4,
  },
  employeeFormSaveText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  employeeFormFields: {
    gap: 10,
  },
  fieldGroup: {
    gap: 8,
  },
  inputLabel: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  input: {
    borderRadius: STOCKY_RADIUS.md,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: STOCKY_COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '500',
  },
  helperText: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  roleInfoCard: {
    borderRadius: STOCKY_RADIUS.md,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: 'rgba(232, 244, 246, 0.55)',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  roleInfoText: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  modalFooterRow: {
    flexDirection: 'row',
    gap: 8,
  },
  modalCancelButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: STOCKY_RADIUS.md,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  modalCancelText: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 13,
    fontWeight: '800',
  },
  modalSaveButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: STOCKY_RADIUS.md,
    backgroundColor: STOCKY_COLORS.primary900,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  modalSaveText: {
    color: STOCKY_COLORS.white,
    fontSize: 13,
    fontWeight: '800',
  },
  modalDangerButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: STOCKY_RADIUS.md,
    backgroundColor: STOCKY_COLORS.errorText,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  modalDangerText: {
    color: STOCKY_COLORS.white,
    fontSize: 13,
    fontWeight: '800',
  },
  deleteText: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  deleteSubtext: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 18,
  },
  credentialsTitle: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
  },
  credentialsCard: {
    borderRadius: STOCKY_RADIUS.md,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 2,
  },
  credentialsLabel: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  credentialsValue: {
    color: STOCKY_COLORS.primary900,
    fontSize: 15,
    fontWeight: '800',
  },
  loadMoreWrap: {
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
  },
  loadMoreHint: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
});
