import { StyleSheet } from 'react-native';
import { STOCKY_COLORS, STOCKY_RADIUS } from '../../../theme/tokens';

export const splitBillStyles = StyleSheet.create({
  modalSheet: {
    borderRadius: 24,
    borderColor: '#E2E8F0',
    maxWidth: 460,
  },
  modalContent: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 14,
  },
  modalScroll: {
    maxHeight: 420,
  },
  modalHeader: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  modalHeaderIcon: {
    width: 36,
    height: 36,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#C7D2FE',
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalHeaderTextWrap: {
    flex: 1,
    gap: 1,
  },
  modalHeaderTitle: {
    color: '#0F172A',
    fontSize: 34,
    fontWeight: '700',
  },
  modalHeaderSubtitle: {
    color: '#64748B',
    fontSize: 19,
    fontWeight: '500',
  },
  helper: {
    fontSize: 18,
    lineHeight: 26,
    fontWeight: '600',
    color: STOCKY_COLORS.textSecondary,
  },
  fieldLabel: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  dropdownWrap: {
    gap: 6,
  },
  dropdownTrigger: {
    minHeight: 46,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dropdownTriggerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  paymentLogo: {
    width: 22,
    height: 14,
  },
  paymentLogoSmall: {
    width: 20,
    height: 12,
  },
  dropdownTriggerText: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 19,
    fontWeight: '600',
  },
  dropdownMenu: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    overflow: 'hidden',
  },
  dropdownItem: {
    minHeight: 44,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148, 163, 184, 0.2)',
  },
  dropdownItemSelected: {
    backgroundColor: '#EEF2FF',
  },
  dropdownItemText: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 18,
    fontWeight: '600',
  },
  dropdownItemTextSelected: {
    color: '#4F46E5',
    fontWeight: '700',
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  stepperItem: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  stepperDot: {
    width: 28,
    height: 28,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperDotActive: {
    borderColor: '#7C3AED',
    backgroundColor: '#F5F3FF',
  },
  stepperDotComplete: {
    borderColor: '#4F46E5',
    backgroundColor: '#EEF2FF',
  },
  stepperDotText: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 16,
    fontWeight: '700',
  },
  stepperDotTextActive: {
    color: '#4F46E5',
  },
  stepperLabel: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 16,
    fontWeight: '700',
  },
  stepperLabelActive: {
    color: '#4F46E5',
  },
  sectionTitle: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 21,
    fontWeight: '800',
  },
  counterCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  counterLabel: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 18,
    fontWeight: '700',
  },
  counterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  counterButton: {
    width: 32,
    height: 32,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: 'rgba(232, 244, 246, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterValue: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 30,
    fontWeight: '800',
    minWidth: 32,
    textAlign: 'center',
  },
  counterHint: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  accountsPreview: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  accountsPreviewChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: 'rgba(232, 244, 246, 0.5)',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  accountsPreviewText: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 16,
    fontWeight: '700',
  },
  itemCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    padding: 12,
    gap: 10,
  },
  assignmentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(102, 165, 173, 0.25)',
    backgroundColor: 'rgba(232, 244, 246, 0.4)',
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  assignmentInfo: {
    flex: 1,
    gap: 1,
    paddingRight: 8,
  },
  assignmentInfoTitle: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 16,
    fontWeight: '700',
  },
  assignmentInfoText: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 16,
    fontWeight: '600',
  },
  assignmentControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  qtyStepButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: 'rgba(232, 244, 246, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyStepText: {
    color: STOCKY_COLORS.primary900,
    fontSize: 20,
    fontWeight: '700',
  },
  qtyValueBadge: {
    borderRadius: 9,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    paddingHorizontal: 8,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 44,
  },
  qtyValueText: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  accountTotalDueRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: 'rgba(232, 244, 246, 0.45)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  accountTotalDueLabel: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 14,
    fontWeight: '700',
  },
  accountTotalDueValue: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 20,
    fontWeight: '800',
  },
  footerRow: {
    flexDirection: 'row',
    gap: 10,
  },
  modalFooter: {
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  actionButtonWrap: {
    flex: 1,
    borderRadius: STOCKY_RADIUS.md,
    overflow: 'hidden',
  },
  actionButton: {
    minHeight: 46,
    borderRadius: STOCKY_RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    flexDirection: 'row',
    gap: 6,
  },
  actionButtonDisabled: {
    opacity: 0.7,
  },
  actionButtonText: {
    color: '#E9D5FF',
    fontSize: 16,
    fontWeight: '800',
  },
  secondaryButton: {
    minHeight: 46,
    borderRadius: STOCKY_RADIUS.md,
    borderWidth: 1,
    borderColor: '#D1D9E2',
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    flex: 1,
  },
  secondaryButtonText: {
    color: STOCKY_COLORS.primary900,
    fontSize: 16,
    fontWeight: '800',
  },
});
