import { StyleSheet } from 'react-native';
import { STOCKY_COLORS, STOCKY_RADIUS } from '../../theme/tokens';

export const comprasStyles = StyleSheet.create({
  screenList: {
    flex: 1,
  },
  container: {
    gap: 16,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 26,
  },
  heroCard: {
    borderRadius: 22,
    padding: 18,
    gap: 16,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 5,
  },
  heroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  heroIconBox: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTitleWrap: {
    flex: 1,
    gap: 2,
  },
  heroTitle: {
    color: '#E5E7EB',
    fontSize: 25,
    fontWeight: '800',
  },
  heroSubtitle: {
    color: '#D1D5DB',
    fontSize: 16,
    fontWeight: '500',
  },
  heroCreateButton: {
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  heroCreateButtonText: {
    color: '#D1D5DB',
    fontSize: 16,
    fontWeight: '600',
  },
  paginationCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 16,
    gap: 14,
    alignItems: 'center',
  },
  paginationText: {
    color: '#4B5563',
    fontSize: 19,
    fontWeight: '500',
    textAlign: 'center',
  },
  paginationControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  paginationArrowButton: {
    width: 58,
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  paginationArrowButtonActive: {
    borderColor: '#C7D2FE',
    backgroundColor: '#EEF2FF',
  },
  paginationPageBadge: {
    minHeight: 42,
    minWidth: 154,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  paginationPageText: {
    color: '#374151',
    fontSize: 17,
    fontWeight: '600',
  },
  saleCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#D8E2EC',
    backgroundColor: '#FFFFFF',
    padding: 18,
    gap: 14,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  saleDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  saleDateText: {
    color: '#1F2937',
    fontSize: 17,
    fontWeight: '500',
  },
  saleInfoGrid: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  saleInfoColumn: {
    flex: 1,
    minWidth: 0,
    gap: 10,
  },
  saleInfoColumnRight: {
    alignItems: 'flex-end',
  },
  saleMetaBlock: {
    gap: 3,
  },
  saleMetaLabel: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  saleMetaValue: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '700',
  },
  paymentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  paymentPill: {
    borderRadius: 999,
    backgroundColor: '#D1FAE5',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  paymentIcon: {
    marginRight: 4,
  },
  paymentIconLogo: {
    width: 20,
    height: 12,
    marginRight: 4,
  },
  paymentPillText: {
    color: '#166534',
    fontSize: 12,
    fontWeight: '700',
  },
  saleTotalBlock: {
    alignItems: 'flex-end',
    gap: 2,
  },
  saleCardTotalLabel: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  saleCardTotalValue: {
    color: '#111827',
    fontSize: 19,
    fontWeight: '800',
  },
  saleActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  saleActionHalf: {
    flex: 1,
  },
  saleDetailsButton: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#475569',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.11,
    shadowRadius: 10,
    elevation: 4,
  },
  saleDetailsText: {
    color: '#D1D5DB',
    fontSize: 14,
    fontWeight: '600',
  },
  saleDeleteButton: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#FF002A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.11,
    shadowRadius: 10,
    elevation: 4,
  },
  saleDeleteText: {
    color: '#FEE2E2',
    fontSize: 14,
    fontWeight: '700',
  },
  purchaseOrderModalSheet: {
    maxHeight: '88%',
    height: '88%',
    borderRadius: 26,
    borderColor: '#D9DEE8',
  },
  purchaseOrderModalHeader: {
    minHeight: 84,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  purchaseOrderModalHeaderIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  purchaseOrderModalHeaderTitle: {
    flex: 1,
    color: '#111827',
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '800',
  },
  purchaseOrderModalHeaderClose: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  purchaseOrderModalContent: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  purchaseOrderModalFooter: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#F3F4F6',
  },
  purchaseOrderFooterContainer: {
    gap: 10,
  },
  purchaseOrderFooterTotalBlock: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 6,
    flexWrap: 'wrap',
  },
  purchaseOrderFooterTotalLabel: {
    color: '#374151',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  purchaseOrderFooterTotalValue: {
    color: '#0F172A',
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '800',
  },
  purchaseOrderSecondaryButton: {
    minHeight: 40,
    borderRadius: STOCKY_RADIUS.md,
    borderWidth: 1,
    borderColor: '#C4B5FD',
    backgroundColor: '#EDE9FE',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    flex: 1,
  },
  purchaseOrderSecondaryButtonText: {
    color: '#5B21B6',
    fontSize: 12,
    fontWeight: '800',
  },
  purchaseOrderPrimaryButton: {
    minHeight: 40,
    borderRadius: STOCKY_RADIUS.md,
    backgroundColor: '#6D28D9',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    flex: 1,
  },
  purchaseOrderPrimaryButtonText: {
    color: '#F5F3FF',
    fontSize: 12,
    fontWeight: '800',
  },
  purchaseOrderBlock: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    padding: 10,
    gap: 8,
  },
  purchaseOrderBlockHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  purchaseOrderBlockTitle: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
  },
  purchaseOrderBlockHint: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
    maxWidth: '54%',
    textAlign: 'right',
  },
  catalogSearchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 2,
  },
  catalogSearchHeaderText: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  catalogResultsCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#DCE2E8',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  catalogResultRow: {
    minHeight: 62,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  catalogResultRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  catalogResultLeft: {
    flex: 1,
    gap: 2,
  },
  catalogResultName: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '600',
  },
  catalogResultMeta: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
  },
  catalogResultRight: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  catalogResultPrice: {
    color: '#16A34A',
    fontSize: 14,
    fontWeight: '700',
  },
  orderItemsTitle: {
    color: '#111827',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 10,
  },
  orderItemsEmpty: {
    minHeight: 130,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  orderItemsEmptyText: {
    color: '#1F2937',
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
  },
  orderItemCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  orderItemTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  orderItemName: {
    flex: 1,
    color: '#111827',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
  },
  orderItemTotal: {
    color: '#111827',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
  },
  orderItemControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
    paddingTop: 2,
  },
  orderItemStepper: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 3,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  orderItemStepperButton: {
    width: 34,
    height: 32,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#DCE2E8',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 1,
  },
  orderItemMinusText: {
    color: '#BE123C',
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '500',
  },
  orderItemPlusText: {
    color: '#16A34A',
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '500',
  },
  orderItemQtyText: {
    minWidth: 34,
    textAlign: 'center',
    color: '#111827',
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '600',
  },
  purchasePaymentBlock: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    padding: 10,
    gap: 8,
  },
  purchasePaymentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  purchasePaymentTitle: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
  },
  purchasePaymentHint: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
  },
  helperText: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  emptyText: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  emptyTextLarge: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  modalLoadingInline: {
    minHeight: 68,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  searchInput: {
    borderRadius: STOCKY_RADIUS.md,
    borderWidth: 1.5,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: STOCKY_COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '500',
  },
  stockManagementHint: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '600',
    fontStyle: 'italic',
    marginTop: -4,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  filterChipSelected: {
    borderColor: STOCKY_COLORS.primary700,
    backgroundColor: 'rgba(7, 87, 91, 0.14)',
  },
  filterChipText: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 11,
    fontWeight: '700',
  },
  filterChipTextSelected: {
    color: STOCKY_COLORS.primary900,
  },
  saleActions: {
    flexDirection: 'row',
    gap: 8,
  },
  secondaryButton: {
    minHeight: 40,
    borderRadius: STOCKY_RADIUS.md,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    flex: 1,
  },
  secondaryButtonText: {
    color: STOCKY_COLORS.primary900,
    fontSize: 12,
    fontWeight: '800',
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  modalOptionItem: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  modalOptionItemSelected: {
    borderColor: '#7C3AED',
    backgroundColor: 'rgba(124, 58, 237, 0.08)',
  },
  modalOptionItemText: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 14,
    fontWeight: '600',
  },
  modalOptionItemTextSelected: {
    color: '#5B21B6',
    fontWeight: '700',
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 8,
  },
  purchaseDetailsModalSheet: {
    width: '100%',
    maxWidth: 470,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#DCE2E8',
    backgroundColor: '#FFFFFF',
  },
  purchaseDetailsContentContainer: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 8,
    gap: 12,
  },
  purchaseDetailsFooter: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  purchaseDetailsHeader: {
    minHeight: 72,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  purchaseDetailsHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  purchaseDetailsHeaderIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  purchaseDetailsHeaderTextWrap: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  purchaseDetailsHeaderTitle: {
    color: '#F5F3FF',
    fontSize: 18,
    fontWeight: '800',
  },
  purchaseDetailsHeaderSubtitle: {
    color: '#DDD6FE',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.4,
  },
  purchaseDetailsHeaderClose: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  purchaseDetailsHeroCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D8E2EC',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    paddingVertical: 11,
    gap: 10,
  },
  purchaseDetailsHeroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  purchaseDetailsHeroTotalWrap: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  purchaseDetailsHeroLabel: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  purchaseDetailsHeroTotal: {
    color: '#0F172A',
    fontSize: 24,
    fontWeight: '800',
  },
  purchaseDetailsHeroMethodBadge: {
    minHeight: 28,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  purchaseDetailsHeroMethodBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  purchaseDetailsHeroMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  purchaseDetailsHeroMetaItem: {
    minHeight: 30,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    maxWidth: '100%',
  },
  purchaseDetailsHeroMetaText: {
    color: '#334155',
    fontSize: 11,
    fontWeight: '600',
  },
  purchaseDetailsNoteCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  purchaseDetailsNoteLabel: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.35,
  },
  purchaseDetailsNoteText: {
    color: '#1F2937',
    fontSize: 12,
    fontWeight: '500',
  },
  purchaseDetailsItemsSectionHeader: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  purchaseDetailsItemsSectionTitle: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '800',
  },
  purchaseDetailsItemsCountBadge: {
    minHeight: 24,
    borderRadius: 999,
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#C7D2FE',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  purchaseDetailsItemsCountText: {
    color: '#4338CA',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  purchaseDetailsListCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#DCE2E8',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 3,
  },
  purchaseDetailsListRow: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  purchaseDetailsListRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F7',
  },
  purchaseDetailsListRowLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  purchaseDetailsQtyBadge: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#C7D2FE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  purchaseDetailsQtyBadgeText: {
    color: '#4338CA',
    fontSize: 12,
    fontWeight: '800',
  },
  purchaseDetailsListMain: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  purchaseDetailsListName: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '700',
  },
  purchaseDetailsListMeta: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
  },
  purchaseDetailsListSubtotal: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
  },
  purchaseDetailsListFooter: {
    minHeight: 44,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  purchaseDetailsListFooterLabel: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '700',
  },
  purchaseDetailsListFooterValue: {
    color: '#0F172A',
    fontSize: 16,
    fontWeight: '800',
  },
});
