import { StyleSheet } from 'react-native';
import { STOCKY_COLORS, STOCKY_RADIUS } from '../../theme/tokens';

export const combosStyles = StyleSheet.create({
  screenList: {
    flex: 1,
  },
  screenListContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 26,
  },
  listHeader: {
    paddingBottom: 16,
  },
  container: {
    gap: 16,
  },
  listItemSeparator: {
    height: 16,
  },
  listFooterSpacer: {
    height: 4,
  },
  heroCard: {
    borderRadius: 22,
    padding: 18,
    gap: 16,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 5,
  },
  heroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  heroIconBox: {
    width: 78,
    height: 78,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTitleWrap: {
    flex: 1,
    gap: 4,
  },
  heroTitle: {
    color: '#D1D5DB',
    fontSize: 22,
    fontWeight: '800',
  },
  heroSubtitle: {
    color: '#D1D5DB',
    fontSize: 14,
    fontWeight: '500',
  },
  heroCreateButton: {
    minHeight: 46,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  heroCreateButtonText: {
    color: '#D1D5DB',
    fontSize: 16,
    fontWeight: '600',
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  errorCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: '#FEF2F2',
  },
  errorText: {
    color: '#991B1B',
    fontSize: 12,
    fontWeight: '600',
    flex: 1,
  },
  emptyText: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  comboCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#D8E2EC',
    backgroundColor: '#FFFFFF',
    padding: 12,
    gap: 8,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  comboHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  comboNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  comboTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
    flex: 1,
  },
  comboTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  comboDescription: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '500',
  },
  divider: {
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  statusBadge: {
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  statusActive: {
    backgroundColor: '#ECFDF3',
    borderColor: '#A6F4C5',
  },
  statusInactive: {
    backgroundColor: '#F2F4F7',
    borderColor: '#D0D5DD',
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  statusActiveText: {
    color: '#067647',
  },
  statusInactiveText: {
    color: '#344054',
  },
  comboCountTag: {
    borderRadius: 999,
    backgroundColor: '#DBEAFE',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  comboCountTagText: {
    color: '#1D4ED8',
    fontSize: 11,
    fontWeight: '600',
  },
  comboInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  comboInfoCell: {
    width: '48%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 8,
    paddingVertical: 7,
    gap: 4,
    alignItems: 'center',
  },
  comboInfoCellFull: {
    width: '100%',
  },
  comboMetaTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  metaLabel: {
    color: '#374151',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metaValue: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  compositionTitle: {
    color: '#1F2937',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    width: '100%',
  },
  compositionText: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 16,
    textAlign: 'center',
    width: '100%',
  },
  comboActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  comboActionHalf: {
    flex: 1,
  },
  comboEditButton: {
    minHeight: 38,
    borderRadius: 12,
    backgroundColor: '#2563EB',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.11,
    shadowRadius: 10,
    elevation: 4,
  },
  comboEditButtonText: {
    color: '#DDE6FF',
    fontSize: 13,
    fontWeight: '600',
  },
  comboDeleteButton: {
    minHeight: 38,
    borderRadius: 12,
    backgroundColor: '#FF002A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.11,
    shadowRadius: 10,
    elevation: 4,
  },
  comboDeleteButtonText: {
    color: '#FFE4E6',
    fontSize: 13,
    fontWeight: '600',
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
  },
  filterChip: {
    flex: 1,
    minHeight: 36,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  filterChipSelected: {
    backgroundColor: 'rgba(102, 165, 173, 0.2)',
    borderColor: STOCKY_COLORS.accent500,
  },
  filterChipText: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  filterChipTextSelected: {
    color: STOCKY_COLORS.primary900,
  },
  comboFormSheet: {
    maxHeight: '88%',
    height: '88%',
    borderRadius: 26,
    borderColor: '#D9DEE8',
  },
  comboFormContent: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  comboFormHeader: {
    minHeight: 84,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  comboFormHeaderIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  comboFormHeaderTitle: {
    flex: 1,
    color: '#111827',
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '800',
  },
  comboFormHeaderClose: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  comboFormFooter: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#F3F4F6',
  },
  comboFormFooterRow: {
    flexDirection: 'row',
    gap: 8,
  },
  comboFormCancelButton: {
    minHeight: 40,
    borderRadius: STOCKY_RADIUS.md,
    borderWidth: 1,
    borderColor: '#C4B5FD',
    backgroundColor: '#EDE9FE',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    flex: 1,
  },
  comboFormCancelButtonText: {
    color: '#5B21B6',
    fontSize: 12,
    fontWeight: '800',
  },
  comboFormSaveButton: {
    minHeight: 40,
    borderRadius: STOCKY_RADIUS.md,
    backgroundColor: '#6D28D9',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
    flex: 1,
  },
  comboFormSaveButtonText: {
    color: '#F5F3FF',
    fontSize: 12,
    fontWeight: '800',
  },
  comboFormFields: {
    gap: 10,
  },
  comboFormRow: {
    flexDirection: 'row',
    gap: 10,
  },
  comboFormCol: {
    flex: 1,
  },
  modalSection: {
    gap: 8,
  },
  inputLabel: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  input: {
    borderRadius: STOCKY_RADIUS.md,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: STOCKY_COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '500',
  },
  textArea: {
    minHeight: 84,
    textAlignVertical: 'top',
  },
  comboItemsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  comboAddItemButton: {
    minHeight: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#C7D2FE',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  comboAddItemButtonText: {
    color: '#4338CA',
    fontSize: 12,
    fontWeight: '700',
  },
  comboItemsList: {
    gap: 9,
  },
  comboItemRowWrap: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 6,
  },
  comboItemEditorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  comboItemSelect: {
    flex: 1,
    minHeight: 43,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  comboItemSelectText: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
  comboItemSelectPlaceholder: {
    color: '#9CA3AF',
    fontWeight: '500',
  },
  comboItemQtyInput: {
    width: 92,
    minHeight: 43,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    color: '#111827',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  comboItemRemoveButton: {
    width: 43,
    height: 43,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  comboItemMeta: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '500',
  },
  comboFieldError: {
    color: '#B91C1C',
    fontSize: 12,
    fontWeight: '600',
  },
  comboSummaryBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#C7D2FE',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 5,
  },
  comboSummaryTitle: {
    color: '#3730A3',
    fontSize: 12,
    fontWeight: '800',
  },
  comboSummaryText: {
    color: '#4338CA',
    fontSize: 12,
    fontWeight: '600',
  },
  comboPickerItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
    gap: 2,
  },
  comboPickerItemSelected: {
    borderColor: '#6366F1',
    backgroundColor: '#EEF2FF',
  },
  comboPickerItemDisabled: {
    opacity: 0.5,
  },
  comboPickerItemTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '700',
  },
  comboPickerItemTitleSelected: {
    color: '#3730A3',
  },
  comboPickerItemMeta: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '500',
  },
  comboPickerItemMetaSelected: {
    color: '#4F46E5',
  },
});
