import { StyleSheet } from 'react-native';
import { STOCKY_COLORS, STOCKY_RADIUS } from '../../theme/tokens';

export const reportesStyles = StyleSheet.create({
  container: {
    gap: 10,
  },
  loadingContainer: {
    minHeight: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroCard: {
    borderRadius: 20,
    padding: 12,
    gap: 10,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
    elevation: 6,
  },
  heroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  heroIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTextWrap: {
    flex: 1,
    gap: 1,
  },
  heroTitle: {
    color: '#E5E7EB',
    fontSize: 20,
    fontWeight: '800',
  },
  heroSubtitle: {
    color: '#D1D5DB',
    fontSize: 12,
    fontWeight: '500',
  },
  heroMeta: {
    color: '#CBD5E1',
    fontSize: 11,
    fontWeight: '500',
  },
  heroBottom: {
    gap: 4,
  },
  refreshButton: {
    minHeight: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  refreshButtonText: {
    color: '#D1D5DB',
    fontSize: 12,
    fontWeight: '600',
  },
  periodCard: {
    borderRadius: STOCKY_RADIUS.lg,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    padding: 10,
    gap: 8,
  },
  sectionTitle: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  periodGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  periodItem: {
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    borderRadius: STOCKY_RADIUS.md,
    minHeight: 32,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: STOCKY_COLORS.surface,
  },
  periodItemSelected: {
    backgroundColor: 'rgba(37, 99, 235, 0.14)',
    borderColor: '#2563EB',
  },
  periodText: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  periodTextSelected: {
    color: '#1D4ED8',
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  kpiCard: {
    flexBasis: '48%',
    flexGrow: 1,
    borderRadius: STOCKY_RADIUS.lg,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    padding: 10,
    gap: 4,
  },
  kpiIconBlue: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#DBEAFE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kpiIconPurple: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#EDE9FE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kpiIconGreen: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#D1FAE5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kpiIconSlate: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kpiLabel: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  kpiValue: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  kpiMoney: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 13,
    fontWeight: '800',
  },
  kpiDanger: {
    color: '#B91C1C',
  },
  blockCard: {
    borderRadius: STOCKY_RADIUS.lg,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    padding: 10,
    gap: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryLabel: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  summaryValue: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 13,
    fontWeight: '800',
  },
  breakdownItem: {
    gap: 4,
  },
  breakdownTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  breakdownLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  breakdownLogo: {
    width: 20,
    height: 12,
  },
  breakdownLabel: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  breakdownValue: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 12,
    fontWeight: '800',
  },
  breakdownMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  breakdownMeta: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 10,
    fontWeight: '600',
  },
  progressTrack: {
    width: '100%',
    height: 6,
    borderRadius: 999,
    backgroundColor: '#E2E8F0',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: STOCKY_COLORS.primary700,
  },
  chartWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(102, 165, 173, 0.22)',
    backgroundColor: '#F8FCFD',
    paddingVertical: 6,
  },
  chartSurface: {
    borderRadius: 12,
  },
  chartCaption: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 10,
    fontWeight: '600',
    marginTop: -2,
  },
  sellerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  rankBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rankText: {
    color: '#334155',
    fontSize: 10,
    fontWeight: '800',
  },
  sellerMain: {
    flex: 1,
    gap: 1,
  },
  sellerName: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  sellerMeta: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 10,
    fontWeight: '600',
  },
  sellerTotal: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 12,
    fontWeight: '800',
  },
  insightRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  insightText: {
    flex: 1,
    color: STOCKY_COLORS.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 15,
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  emptyText: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '600',
  },
});
