import { StyleSheet } from 'react-native';
import { STOCKY_COLORS, STOCKY_RADIUS } from '../../theme/tokens';

export const configuracionStyles = StyleSheet.create({
  container: {
    gap: 12,
  },
  loadingContainer: {
    minHeight: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageIntroCard: {
    borderRadius: STOCKY_RADIUS.lg,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: '#003B46',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 3,
  },
  pageIntroIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageIntroTextWrap: {
    flex: 1,
    gap: 2,
  },
  pageIntroTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: STOCKY_COLORS.textPrimary,
  },
  pageIntroSubtitle: {
    fontSize: 11,
    fontWeight: '500',
    color: STOCKY_COLORS.textSecondary,
  },
  sectionCard: {
    borderRadius: STOCKY_RADIUS.lg,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    overflow: 'hidden',
    shadowColor: '#003B46',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 3,
  },
  sectionHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  sectionHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sectionHeaderIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionHeaderTextWrap: {
    flex: 1,
    gap: 1,
  },
  sectionHeaderTitle: {
    color: '#D1D5DB',
    fontSize: 20,
    fontWeight: '800',
  },
  sectionHeaderSubtitle: {
    color: '#CBD5E1',
    fontSize: 11,
    fontWeight: '500',
  },
  sectionHeaderAction: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  sectionHeaderActionText: {
    color: '#D1D5DB',
    fontSize: 12,
    fontWeight: '700',
  },
  sectionBody: {
    padding: 12,
    gap: 10,
  },
  infoItem: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    padding: 12,
    gap: 8,
  },
  infoTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  infoLabel: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '600',
  },
  infoValue: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  signOutButton: {
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FEE2E2',
    backgroundColor: '#FEF2F2',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  signOutText: {
    color: '#B91C1C',
    fontSize: 13,
    fontWeight: '800',
  },
  deleteAccountButton: {
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: '#FFF1F2',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  deleteAccountText: {
    color: '#DC2626',
    fontSize: 13,
    fontWeight: '800',
  },
  systemItem: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    padding: 12,
    gap: 8,
  },
  systemInfoBlue: {
    backgroundColor: '#DFEAFE',
  },
  systemInfoPurple: {
    backgroundColor: '#F3E8FF',
  },
  systemInfoGreen: {
    backgroundColor: '#DCFCE7',
  },
  systemTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  systemLabel: {
    fontSize: 12,
    fontWeight: '700',
  },
  systemValue: {
    fontSize: 17,
    fontWeight: '800',
  },
  systemBlueText: {
    color: '#1E3A8A',
  },
  systemPurpleText: {
    color: '#6B21A8',
  },
  systemGreenText: {
    color: '#065F46',
  },
  legalCard: {
    borderRadius: STOCKY_RADIUS.lg,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    overflow: 'hidden',
    shadowColor: '#003B46',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 3,
  },
  legalHeader: {
    backgroundColor: '#0F172A',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  legalHeaderIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  legalHeaderTextWrap: {
    flex: 1,
    gap: 2,
  },
  legalHeaderTitle: {
    color: '#E2E8F0',
    fontSize: 18,
    fontWeight: '800',
  },
  legalHeaderSubtitle: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '500',
  },
  legalBody: {
    padding: 12,
    gap: 10,
  },
  legalButton: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  legalButtonIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  legalButtonTextWrap: {
    flex: 1,
    gap: 2,
  },
  legalButtonTitle: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
  },
  legalButtonSubtitle: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '500',
  },
  businessEditSheet: {
    maxWidth: 760,
    maxHeight: '90%',
    borderRadius: 22,
    borderColor: '#D6DDE7',
    backgroundColor: '#FFFFFF',
  },
  businessEditHeader: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  businessEditHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  businessEditHeaderIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  businessEditHeaderTextWrap: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  businessEditHeaderTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
  businessEditHeaderSubtitle: {
    color: '#E2E8F0',
    fontSize: 12,
    fontWeight: '500',
  },
  businessEditHeaderClose: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  businessEditFooter: {
    backgroundColor: '#FFFFFF',
    borderTopColor: '#E5E7EB',
    borderTopWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  businessEditFooterRow: {
    flexDirection: 'row',
    gap: 10,
  },
  businessEditCancelButton: {
    minHeight: 45,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D7DEE8',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  businessEditCancelText: {
    color: '#1F2937',
    fontSize: 14,
    fontWeight: '700',
  },
  businessEditSaveWrap: {
    flex: 1,
  },
  businessEditSaveButton: {
    minHeight: 45,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 4,
  },
  businessEditSaveText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  businessEditFields: {
    gap: 10,
  },
  businessEditField: {
    gap: 6,
  },
  businessEditLabel: {
    color: STOCKY_COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  businessEditInput: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: STOCKY_COLORS.surface,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: STOCKY_COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '500',
  },
  businessEditReadOnlyBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: STOCKY_COLORS.borderSoft,
    backgroundColor: '#F9FAFB',
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'center',
    minHeight: 46,
  },
  businessEditReadOnlyText: {
    color: STOCKY_COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  businessEditTextArea: {
    minHeight: 86,
    textAlignVertical: 'top',
  },
  deleteAccountSheet: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    overflow: 'hidden',
  },
  deleteAccountHeader: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  deleteAccountHeaderIcon: {
    height: 40,
    width: 40,
    borderRadius: 14,
    backgroundColor: 'rgba(220, 38, 38, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteAccountTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#7F1D1D',
  },
  deleteAccountSubtitle: {
    fontSize: 12,
    color: '#7F1D1D',
  },
  deleteAccountBody: {
    padding: 16,
    gap: 10,
  },
  deleteAccountBodyText: {
    fontSize: 12.5,
    color: '#7F1D1D',
    lineHeight: 18,
  },
  deleteAccountFooter: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  deleteAccountFooterRow: {
    flexDirection: 'row',
    gap: 12,
  },
  deleteAccountCancel: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteAccountCancelText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#374151',
  },
  deleteAccountConfirm: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: '#DC2626',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteAccountConfirmText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  footerText: {
    color: STOCKY_COLORS.textMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  disabled: {
    opacity: 0.7,
  },
});
